### PR TITLE
Stats improvements

### PR DESCRIPTION
**Pull request by j-px**
Some really minor stats improvements. Feel free to complain, but they reduce ambiguity by use of wrong or nonexistent units.

### CODE REVIEW

**Comment by PranavPurwar** [comment]
why use `10 ms` aaa `10ms` is better

**Comment by j-px** [comment]
Commit af3ec8b66eed8d8c45958f826ea3af6baaf4e025: "Add space between quantity and unit in stats"'s message explains why.

**Comment by PranavPurwar** [comment]
do not care about dumb international recommendations

**Comment by j-px** [comment]
It's not just "recommendations", those are standards. Also, I don't think it really matters here that you don't care about that.

**Comment by khaled-0** [comment]
My whole life has been a lie

**Comment by j-px** [comment]
since there's just a few reactions available

😔

**Comment by khaled-0** [comment]
> since there's just a few reactions available
> 
> 😔

I don't even have a reaction button visible on mobile website.

**Pull request merged**
